menambahkan dockerfile dan docker-image
C23-PS419/petanikita-api pull request #19
Opened 2023-06-06 12:46 UTC by sisiliaa01

menambahkan konfigurasi Dockerfile dan docker-image.yml untuk konfigurasi CI/CD

2023-06-06 13:11 UTC, risangbaskoro commented
What are env var keys that needed for deployment?

2023-06-06 13:17 UTC, risangbaskoro commented on .github/workflows/docker-image.yml
> +    branches: ["petanitest"]
Change branch name to "master" since we only deploy to production when master there are commits to that remote branch

2023-06-06 13:20 UTC, risangbaskoro commented on .github/workflows/docker-image.yml
> +        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region asia-southeast2 --platform managed --port 80 --allow-unauthenticated --set-env-vars="DB_DATABASE=${{ secrets.
If possible, please make this command multiline so it's easier to read.

2023-06-06 13:24 UTC, sisiliaa01 commented
well, this is the Key : 
GCP_PROJECT_ID
GCP_EMAIL
GCP_CREDENTIALS
GCP_APP_NAME
DB_DATABASE
DB_USERNAME
DB_PASSWORD
DB_HOST
APP_KEY
APP_DEBUG
APP_NAME
APP_ENV

The value ill be inform by personal chat

2023-06-07 04:18 UTC, risangbaskoro approved these changes

2023-06-07 04:54 UTC, risangbaskoro requested changes
Do not delete the pint file

2023-06-07 05:01 UTC, risangbaskoro requested changes

2023-06-07 05:01 UTC, risangbaskoro commented on .github/workflows/docker-image.yml
> +    branches: ["master"]
You can try 
```yaml
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["deploy-gcp"]
```
if you want to test it on this branch. After that, you need to delete those line you just created.

2023-06-07 05:01 UTC, risangbaskoro commented on .github/workflows/docker-image.yml
> +name: Docker Image CI
Change the name of the workflow to something useful, like "Build Docker Image and Deploy to Google Cloud" or something.

2023-06-07 05:04 UTC, risangbaskoro submitted a review, later dismissed

2023-06-07 05:04 UTC, risangbaskoro commented on .github/workflows/docker-image.yml
> +          #test
Delete this line.

2023-06-07 05:18 UTC, risangbaskoro requested changes

2023-06-07 05:18 UTC, risangbaskoro commented on .github/workflows/docker-image.yml
> +      - deploy-gcp
These lines:
```yaml
  pull_request:
    branches:
      - deploy-gcp
```
need to be deleted.

2023-06-08 03:36 UTC, dimas-ishaq commented
@risangbaskoro done

2023-06-08 05:50 UTC, risangbaskoro approved these changes

2023-06-08 05:51 UTC, merged